version: '3.6'

services:
  backend:
    restart: always
    build:
      context: ./backend/chartjs
      dockerfile: Dockerfile      
    command: bash -c "gunicorn chartjs.wsgi --bind 0.0.0.0:8000"
    container_name: backend
    image: backend_image
    volumes:
      - ./backend/chartjs:/backend
    ports:
      - '8000:8000'

  frontend:
    restart: always
    build:  
      context: ./frontend/chartjs_app
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend_image
    depends_on:
      - backend
    volumes:
      - ./frontend/chartjs_app/nginx:/etc/nginx/conf.d
    ports:
      - 8001:80
